# Generated by Django 6.0.6 on 2026-07-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaLibre', '0002_categoria_producto_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
