# Generated by Django 6.0.6 on 2026-07-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaLibre', '0003_remove_producto_imagen_producto_imagen_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen_url',
            new_name='imagen',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
