# Generated by Django 6.0.6 on 2026-07-29 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaLibre', '0004_rename_imagen_url_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'productos'},
        ),
    ]
