# Generated by Django 6.0.6 on 2026-09-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaLibre', '0005_alter_producto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
